mzconduct: merge into mzcompose
Merge mzconduct and mzcompose. Where you previously ran

    $ bin/mzconduct chbench --workflow=ci

you now run:

    $ cd demo/chbench && ./mzcompose run ci

The hope is that the new API is less confusing to users. Everything
happens locally in the demo/test directory, so you no longer need to
reach out to ../../bin/mzconduct for some commands and ./mzcompose for
others.

The code is also greatly simplified, since we no longer have two
separate programs that need to parse and understand mzcompose.yml files.

diff --git a/bin/mzconduct b/bin/mzconduct
--- a/bin/mzconduct
+++ b/bin/mzconduct
@@ -15,4 +15,48 @@ set -euo pipefail
 
 cd "$(dirname "$0")/.."
 
-exec bin/pyactivate -m materialize.cli.mzconduct "$@"
+. misc/shlib/shlib.bash
+
+red "WARNING: mzconduct has been merged into mzcompose; this script will be removed soon\n" >&2
+echo 'hint: cd into the test directory and run ./mzcompose run WORKFLOW instead'
+
+if [[ "${1:-}" != run ]]; then
+    die "compatiblity shim only supports 'run' command"
+fi
+shift
+
+test=
+workflow=
+workflow_next=false
+for arg; do
+    if $workflow_next; then
+        workflow_next=false
+        workflow=$arg
+        continue
+    fi
+    case "$arg" in
+        --workflow=*) workflow=${arg#--workflow=} ;;
+        --workflow|-w) workflow_next=true ;;
+        -*) die "unknown option $arg" ;;
+        *)
+            if [[ "$test" ]]; then
+                die "specifying more than one test is not permitted"
+            fi
+            test=$arg
+        ;;
+    esac
+done
+
+if [[ ! "$workflow" ]]; then
+    die "missing required option --workflow"
+fi
+
+case "$test" in
+    "billing")      cd demo/billing ;;
+    "chaos")        cd test/chaos ;;
+    "chbench")      cd demo/chbench ;;
+    "perf-kinesis") cd test/performance/perf-kinesis ;;
+    *)              die "unknown test $test" ;;
+esac
+
+exec ./mzcompose run "$workflow"
