WIP Add new workflow to verify snapshots work

diff --git a/demo/chbench/kafkasnap/snapshot_topics b/demo/chbench/kafkasnap/snapshot_topics
--- a/demo/chbench/kafkasnap/snapshot_topics
+++ b/demo/chbench/kafkasnap/snapshot_topics
@@ -9,17 +9,18 @@
 # the Business Source License, use of this software will be governed
 # by the Apache License, Version 2.0.
 
-# Script to list and dump all topics from a Kafka cluster
-# Dumps files into the working directory of the script
+# Script to list and dump all topics (and their schemas) from a Kafka cluster
 
 if ! topics=$(kafkacat -L -b kafka:9092 | grep debezium | cut -d '"' -f 2); then
     echo "Failed to list topics!"
     exit 1
 fi
 
+SNAPSHOT_DIR="/snapshot"
+
 jq_filter=".schema"
 for topic in $topics; do
-    schemafile="${topic}.schema"
+    schemafile="${SNAPSHOT_DIR}/${topic}.schema"
     if ! subject=$(curl -s schema-registry:8081/subjects/${topic}-value/versions/latest); then
         echo "Failed to query subject ${topic}"
         exit 1
@@ -32,10 +33,11 @@ for topic in $topics; do
 
     echo "Saved ${topic} schema to file ${schemafile}"
 
-#    if ! kafkacat -C -b kafka:9092 -t "${topic}" -e > "${snapfile}"; then
-#        echo "Failed to dump topic ${topic}"
-#        exit 1
-#    fi
-#    echo "Saved ${topic} to file ${snapfile}"
+    snapfile="${SNAPSHOT_DIR}/${topic}.snap"
+    if ! kafkacat -C -b kafka:9092 -t "${topic}" -e > "${snapfile}"; then
+        echo "Failed to dump topic ${topic}"
+        exit 1
+    fi
+    echo "Saved ${topic} to file ${snapfile}"
 
 done
