ci: Fix cleanup properly
And remove the old workaround which turned out not to be the cause

fixes: https://github.com/MaterializeInc/database-issues/issues/9952

diff --git a/ci/plugins/cloudtest/hooks/command b/ci/plugins/cloudtest/hooks/command
--- a/ci/plugins/cloudtest/hooks/command
+++ b/ci/plugins/cloudtest/hooks/command
@@ -75,7 +75,9 @@ ci_uncollapsed_heading "cloudtest: Running \`$TEST_CMD\`"
 
 cleanup() {
   # Don't run the cleanup function twice
-  trap - EXIT SIGTERM SIGINT
+  trap - EXIT
+  # Keep running cleanup, even if we get cancelled
+  trap '' SIGTERM SIGINT
 
   echo "--- Post command steps"
   # Buildkite exposes no way to check if a test timed out (and wasn't cancelled manually), so we have to calculate it ourselves
@@ -195,8 +197,14 @@ trap cleanup EXIT SIGTERM SIGINT
 # When cancelled, always count as failed!
 TEST_RESULT=1
 # sed command to filter out ANSI command codes in run.log, while keeping them in Buildkite's view
-{ stdbuf --output=L --error=L bin/ci-builder run stable bin/pytest "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); }
-TEST_RESULT=${PIPESTATUS[0]:-1}
+{
+  set -o pipefail
+  stdbuf --output=L --error=L bin/ci-builder run stable bin/pytest "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log);
+} &
+pid=$!
+
+wait "$pid"
+TEST_RESULT=$?
 if [ "$TEST_RESULT" != "0" ]; then
     # Give the logs some time to log panics, otherwise they might be missing later
     sleep 10
diff --git a/ci/plugins/mzcompose/hooks/command b/ci/plugins/mzcompose/hooks/command
--- a/ci/plugins/mzcompose/hooks/command
+++ b/ci/plugins/mzcompose/hooks/command
@@ -93,7 +93,9 @@ echo "$TEST_DESC"
 
 cleanup() {
   # Don't run the cleanup function twice
-  trap - EXIT SIGTERM SIGINT
+  trap - EXIT
+  # Keep running cleanup, even if we get cancelled
+  trap '' SIGTERM SIGINT
 
   # Buildkite exposes no way to check if a test timed out (and wasn't cancelled manually), so we have to calculate it ourselves
   START_TIME=$(date -d "$STEP_START_TIMESTAMP" +%s)
@@ -223,8 +225,6 @@ cleanup() {
   else
     # Ignore failures, we still want the rest of the cleanup
     mzcompose down --timeout=0 --volumes || true
-    # --timeout=0 can keep some alive, so retry in that case
-    mzcompose rm --force --stop --volumes || true
   fi
 
   echo "Finding core files"
@@ -365,9 +365,12 @@ trap cleanup EXIT SIGTERM SIGINT
 # When cancelled, always count as failed!
 TEST_RESULT=1
 # sed command to filter out ANSI command codes in run.log, while keeping them in Buildkite's view
-{ mzcompose run "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); }
-TEST_RESULT=${PIPESTATUS[0]:-1}
-if [ "$TEST_RESULT" != "0" ]; then
-    # Give the logs some time to log panics, otherwise they might be missing later
-    sleep 10
-fi
+{
+  set -o pipefail
+  mzcompose run "${run_args[@]}" \
+    |& tee >(sed -r 's/\x1B\[[0-9;]*[A-Za-z]//g' > run.log)
+} &
+pid=$!
+
+wait "$pid"
+TEST_RESULT=$?
