ci: Consider cancelled jobs as failed consistently
Seen in https://buildkite.com/materialize/test/builds/113307#019b135c-1e21-47c3-b1f1-a5bafd23fa83

diff --git a/ci/plugins/cloudtest/hooks/command b/ci/plugins/cloudtest/hooks/command
--- a/ci/plugins/cloudtest/hooks/command
+++ b/ci/plugins/cloudtest/hooks/command
@@ -72,7 +72,6 @@ NO_COLOR=1 bin/ci-builder run stable --detach --name "kail" kail --context "$K8S
 TEST_CMD="bin/pytest ${run_args[*]}"
 
 ci_uncollapsed_heading "cloudtest: Running \`$TEST_CMD\`"
-TEST_RESULT=0
 
 cleanup() {
   # Don't run the cleanup function twice
@@ -193,8 +192,11 @@ cleanup() {
 
 trap cleanup EXIT SIGTERM SIGINT
 
+# When cancelled, always count as failed!
+TEST_RESULT=1
 # sed command to filter out ANSI command codes in run.log, while keeping them in Buildkite's view
-{ stdbuf --output=L --error=L bin/ci-builder run stable bin/pytest "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); } || TEST_RESULT=$?
+{ stdbuf --output=L --error=L bin/ci-builder run stable bin/pytest "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); }
+TEST_RESULT=${PIPESTATUS[0]:-1}
 if [ "$TEST_RESULT" != "0" ]; then
     # Give the logs some time to log panics, otherwise they might be missing later
     sleep 10
diff --git a/ci/plugins/mzcompose/hooks/command b/ci/plugins/mzcompose/hooks/command
--- a/ci/plugins/mzcompose/hooks/command
+++ b/ci/plugins/mzcompose/hooks/command
@@ -359,9 +359,11 @@ cleanup() {
 
 trap cleanup EXIT SIGTERM SIGINT
 
-TEST_RESULT=0
+# When cancelled, always count as failed!
+TEST_RESULT=1
 # sed command to filter out ANSI command codes in run.log, while keeping them in Buildkite's view
-{ mzcompose run "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); } || TEST_RESULT=$?
+{ mzcompose run "${run_args[@]}" |& tee >(sed -r "s/\x1B\[[0-9;]*[A-Za-z]//g" > run.log); }
+TEST_RESULT=${PIPESTATUS[0]:-1}
 if [ "$TEST_RESULT" != "0" ]; then
     # Give the logs some time to log panics, otherwise they might be missing later
     sleep 10
