ci: Clean up better without sacrificing speed
A normal `mzcompose down` without `--timeout=0` can take very long.

Fixes https://github.com/MaterializeInc/database-issues/issues/9952

diff --git a/ci/plugins/mzcompose/hooks/command b/ci/plugins/mzcompose/hooks/command
--- a/ci/plugins/mzcompose/hooks/command
+++ b/ci/plugins/mzcompose/hooks/command
@@ -221,7 +221,10 @@ cleanup() {
   if [ -n "${CI_COVERAGE_ENABLED:-}" ]; then
     mzcompose down --volumes || true
   else
-    mzcompose down --timeout=0 --volumes || true  # Ignore failures, we still want the rest of the cleanup
+    # Ignore failures, we still want the rest of the cleanup
+    mzcompose down --timeout=0 --volumes || true
+    # --timeout=0 can keep some alive, so retry in that case
+    mzcompose rm --force --stop --volumes || true
   fi
 
   echo "Finding core files"
