ci: Try to wait for core dumps
Seen in https://buildkite.com/materialize/nightlies/builds/6933#018e439d-e26a-4f01-b7b0-39fa665ee25c

diff --git a/ci/plugins/mzcompose/hooks/post-command b/ci/plugins/mzcompose/hooks/post-command
--- a/ci/plugins/mzcompose/hooks/post-command
+++ b/ci/plugins/mzcompose/hooks/post-command
@@ -48,7 +48,8 @@ fi
 
 find cores -name 'core.*' | while read -r core; do
     exe=$(echo "$core" | sed -e "s/core\.\(.*\)\.[0-9]*/\1/" -e "s/.*\!//")
-    bin/ci-builder run stable gdb --batch -ex "bt full" -ex "thread apply all bt" -ex "quit" cores/"$exe" "$core" > "$core".txt || true
+    # Core dumps can take a while to be written, so if extracting the info fails, try again later
+    bin/ci-builder run stable gdb --batch -ex "bt full" -ex "thread apply all bt" -ex "quit" cores/"$exe" "$core" > "$core".txt || (sleep 2m; bin/ci-builder run stable gdb --batch -ex "bt full" -ex "thread apply all bt" -ex "quit" cores/"$exe" "$core" > "$core".txt || true)
     if grep -q "Program terminated with signal SIGABRT, Aborted." "$core".txt; then
         echo "SIGABRT found in \"$core.txt\", ignoring core file"
     else
